language: python
script: pytest
python:
    - "3.6"
env: 
  secure: CODECOV_TOKEN="fe9672dd-1bbc-476a-9a48-4efa7bc73373"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install pylint 
  - pip install black
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install coverage
script:
  - black sat test test_integration --diff --check
  - python -m pylint sat test test_integration --rcfile conf/.pylintrc
  - coverage run --source=sat --branch -m pytest --cov-config=conf/.coveragerc -m "not integration"
after_success:
  - codecov